### ISSUE TITLE
jumping up does not work

### ISSUE THREAD

**Issue by ghost** [msmalik681/amiga-500---shadow-dancer#1]
Hi!

I tried playing the .adf demo on a real Amiga. But I noticed jumping up does not work. Pressing the joystick up does nothing. I tried again on another Amiga and the same problem. So I can't even jump over the  blocks.

I guess it's a bug?

Kind regards,
Hans

**Comment by msmalik681** [comment]
Sorry for the late reply but this is no but this game requires a 2 button joystick or gamepad. Maybe i will add a notification screen to make the user aware.
